apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  jobTemplate:
    metadata:
      name: my-cronjob
    spec:
      template:
        spec:
          containers:
          - image: busybox
            name: my-cronjob
            command: ['sleep', '60']
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
