apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secret-service
  name: secret-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: secret-service
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - args:
        - -c
        - while true; do echo hello; sleep 10;done
        command:
        - /bin/sh
        image: alpine
        imagePullPolicy: Always
        name: alpine
        volumeMounts:
        - mountPath: /etc/users
          name: my-foo
          readOnly: true
      volumes:
      - name: my-foo
        secret:
          secretName: my-secret
