apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: staff
  name: bob-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
