apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: ckad-ns1
  name: ckad-ns3
spec:
  finalizers:
  - kubernetes
status:
  phase: Active

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  namespace: ckad-ns3
data:
  # property-like keys; each key maps to a simple value
  localport: "localhost:8082"
  external_url: "linux.com"

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpine-pod
  name: alpine-pod
  namespace: ckad-ns3
spec:
  containers:
  - image: alpine
    name: alpine-container
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    envFrom:
      - configMapRef:
          name: game-demo
  dnsPolicy: ClusterFirst
  restartPolicy: Always
