apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: ckad-ns1
  name: ckad-ns2
spec:
  finalizers:
  - kubernetes
status:
  phase: Active

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  namespace: ckad-ns2
data:
  # property-like keys; each key maps to a simple value
  localport: "localhost:8082"
  external_url: "linux.com"

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpine-pod
  name: alpine-pod
  namespace: ckad-ns2
spec:
  containers:
  - image: alpine
    name: alpine-container
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    env:
    - name: localport # Notice that the case is different here
      valueFrom:
        configMapKeyRef:
          name: game-demo           # The ConfigMap this value comes from.
          key: localport # The key to fetch.
    - name: external_url
      valueFrom:
        configMapKeyRef:
          name: game-demo
          key: external_url
  dnsPolicy: ClusterFirst
  restartPolicy: Always
